version: "3.9"
services:
    
    ProductContextDb:
        container_name: ProductContextDb
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Password1"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

    integration-tests:
        container_name: integration-tests
        image: mcr.microsoft.com/dotnet/sdk:5.0
        environment:  
          - ConnectionStrings__ProductContextDb=Data Source=ProductContextDb; Initial Catalog=ProductContextDb; User Id=sa; Password=Password1
        volumes: 
          - .:/Product.API.Project
          - ../Product.API.Tests:/Product.API.Tests
        working_dir: /Product.API.Project
        command:
          [
            "dotnet",
            "test"
          ]
        depends_on:
          - ProductContextDb                     