version: "3.9"
services:
    
    ProductContextDb:
        container_name: ProductContextDb
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Password1"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
                         